import { extractJoinerName } from './src/nyatos/ad-pressure.js';
const Database = (await import('better-sqlite3')).default;
const db = new Database('data/xxb.db', { readonly: true });
const rows = db.prepare("select text from bot_interactions where bot_username='nmnmfunbot' and text is not null and text!='' order by rowid desc limit 200").all();
const pass = rows.filter(r => /has passed the group verification/i.test(String(r.text)));
const ban = rows.filter(r => /封禁并向 nmBot 举报/.test(String(r.text)));
let ok = 0;
for (const r of pass) if (extractJoinerName(String(r.text))) ok++;
let leaked = 0;
for (const r of ban) if (extractJoinerName(String(r.text))) leaked++;
console.log('JT2 通过验证 ' + pass.length + ' 条 → 提取 ' + ok);
console.log('JT2 封禁举报 ' + ban.length + ' 条 → 误提取 ' + leaked + '（应为 0）');
db.close(); process.exit(0);
